name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - seaborn
  - missingno
  - sklearn
  - scipy
  - statsmodel
  - warnings
  - os
  - io
  - skimage